DECLARE FUNCTION skinppLoadSkin LIB "SkinPPWTL.dll" ALIAS "skinppLoadSkin" (BYVAL FilName$)AS LONG
DECLARE FUNCTION skinppExitSkin LIB "SkinPPWTL.dll" ALIAS "skinppExitSkin" (BYVAL yes&)AS LONG
DECLARE FUNCTION skinppRemoveSkin LIB "SkinPPWTL.dll" ALIAS "skinppRemoveSkin" (BYVAL yes&)AS LONG
DECLARE FUNCTION skinppRemoveSkinHwnd LIB "SkinPPWTL.dll" ALIAS "skinppRemoveSkinHwnd" (BYVAL yes&)AS LONG


