/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class montnets_MWGateway */

#ifndef _Included_montnets_MWGateway
#define _Included_montnets_MWGateway
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     montnets_MWGateway
 * Method:    Connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_Connect
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     montnets_MWGateway
 * Method:    SendSms
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_SendSms
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     montnets_MWGateway
 * Method:    TestConn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_TestConn
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    QueryBalance
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_QueryBalance
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    QueryUsed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_QueryUsed
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    Recharge
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_Recharge
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     montnets_MWGateway
 * Method:    ChangePwd
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_ChangePwd
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     montnets_MWGateway
 * Method:    Disconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_montnets_MWGateway_Disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    VasGetSms
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_montnets_MWGateway_VasGetSms
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    VasSendSms
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_montnets_MWGateway_VasSendSms
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    CsGetSms
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_montnets_MWGateway_CsGetSms
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    CsGetSmsEx
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_montnets_MWGateway_CsGetSmsEx
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    CsSendSms
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_montnets_MWGateway_CsSendSms
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    CsGetStatusReport
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_montnets_MWGateway_CsGetStatusReport
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    CsGetStatusReportEx
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_montnets_MWGateway_CsGetStatusReportEx
  (JNIEnv *, jclass, jint);

/*
 * Class:     montnets_MWGateway
 * Method:    CsSPSendSms
 * Signature: (ILjava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_montnets_MWGateway_CsSPSendSms
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jstring);

/*
 * Class:     montnets_MWGateway
 * Method:    MGhexChrTosrcStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_montnets_MWGateway_MGhexChrTosrcStr
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
