//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DbGate.rc
//
#define IDC_BTN_MORE                    3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DbGateTYPE                  129
#define IDD_DLG_MAINTOP                 130
#define IDD_DLG_MAINBOTTOM              131
#define IDD_DLG_CLOSE                   132
#define IDD_DLG_ALLSET                  150
#define IDD_DLG_OTHERSET                152
#define IDD_DLG_OTHERSETEX              153
#define IDR_MENU1                       154
#define IDD_DLG_SET_BASE                155
#define IDR_MENU2                       155
#define IDD_DLG_STORESET                156
#define IDR_TOOLBAR                     157
#define IDD_DIALOG1                     159
#define IDD_DIALOG_SINGLESEND           159
#define IDC_LIST1                       1000
#define IDC_LIST_SENT                   1000
#define IDC_EDIT_READSQL                1000
#define IDC_EDIT_SQL                    1000
#define IDC_LIST_DISP                   1001
#define IDC_LIST_REPORT                 1001
#define IDC_EDIT_DBASESERVER            1001
#define IDC_EDIT_READINDEX              1001
#define IDC_TAB_SHOW                    1002
#define IDC_EDIT_DBASEUID               1002
#define IDC_EDIT_ADDSQL                 1002
#define IDC_LIST_RECV                   1003
#define IDC_EDIT_DBASEPWD               1003
#define IDC_TAB_SET                     1003
#define IDC_EDIT_ADDINDEX               1003
#define IDC_INFO_SHOW                   1003
#define IDC_EDIT_DBNAME                 1004
#define IDC_EDIT_UPDATESQL              1004
#define IDC_CHECK1                      1005
#define IDC_EDIT_UPDATEINDEX            1005
#define IDC_CHECK_MAINPORT              1005
#define IDC_EDIT_DBASEPORT              1005
#define IDC_CHECK_ERRORSTOP             1006
#define IDC_CHECK_ERRORRERUN            1006
#define IDC_EDIT_SAVEMOSQL              1006
#define IDC_EDIT_DBASEPORT2             1006
#define IDC_EDIT_DBCHARSET              1006
#define IDC_CHECK_AUTORUN               1007
#define IDC_EDIT_SAVEMOINDEX            1007
#define IDC_EDIT_BUFFLEN                1008
#define IDC_PROGRESS_THREAD             1008
#define IDC_BTN_SAVE                    1008
#define IDC_CHECK_USESUBPORT            1009
#define IDC_EDIT_SPLITELEN              1010
#define IDC_EDIT_TITLE                  1010
#define IDC_COMBO_PORT                  1011
#define IDC_EDIT_PHONESPLITELEN         1011
#define IDC_EDIT_TITLE2                 1011
#define IDC_CHECK_RECVMO                1012
#define IDC_CHECK_RECVREPORT            1013
#define IDC_EDIT_SENDTHREADNUM          1014
#define IDC_CHECK_AUTORUN2              1014
#define IDC_CHECK_RUNCTRL               1014
#define IDC_CHECK_NUMHEAD               1014
#define IDC_CHECK_HEADDIFFER            1014
#define IDC_CHECK_DIFFMOBILE            1014
#define IDC_EDIT_SENDINTERVAL           1015
#define IDC_EDIT_SENDNULLWAIT           1016
#define IDC_EDIT_ACCOUNT                1017
#define IDC_EDIT_ACCPWD                 1018
#define IDC_EDIT_TIMESTART1             1019
#define IDC_EDIT_ERRORSTOPTIME          1019
#define IDC_EDIT_TIMEEND1               1020
#define IDC_CHECK_AUTORUN3              1020
#define IDC_CHECK_LOG                   1020
#define IDC_EDIT1                       1020
#define IDC_EDIT_READNULLWAIT           1021
#define IDC_EDIT_TIMESTART5             1021
#define IDC_COMBO_                      1021
#define IDC_EDIT_RECVSTATUS4            1021
#define IDC_CHECK_DIFFMOBILE2           1021
#define IDC_CHECK_KEYCHECK              1021
#define IDC_EDIT_CONTENT                1021
#define IDC_EDIT_ACCPWD5                1022
#define IDC_EDIT_TIMEEND5               1022
#define IDC_BTN_READADD                 1022
#define IDC_EDIT_RECVSTATUS             1022
#define IDC_EDIT_PHONEFILEPATH          1022
#define IDC_EDIT_ADDINTERVAL            1023
#define IDC_BTN_ADDMODIFY               1023
#define IDC_EDIT_RECVSTATUS2            1023
#define IDC_EDIT_ADDNULLWAIT            1024
#define IDC_LIST_MAPPING                1024
#define IDC_EDIT_RECVSTATUS5            1024
#define IDC_EDIT_ADDBUFFULLWAIT         1025
#define IDC_COMBO_SQL                   1025
#define IDC_RADIO_NORMAL                1025
#define IDC_EDIT_PHONEFILEPATH2         1025
#define IDC_EDIT_WINDOWNAME             1025
#define IDC_EDIT_SERVERIP               1026
#define IDC_EDIT2                       1026
#define IDC_RADIO_OWNSET                1026
#define IDC_EDIT_SERVERPORT             1027
#define IDC_RADIO_DBSTORESET            1027
#define IDC_EDIT_TIMESTART3             1028
#define IDC_EDIT_READONETIME            1028
#define IDC_EDIT_SENDSTATUS2            1028
#define IDC_EDIT_RECVMOINTERVAL         1028
#define IDC_EDIT_TIMEEND3               1029
#define IDC_FRAME_BASE                  1029
#define IDC_EDIT_RECVREPORTINTERVAL     1029
#define IDC_EDIT_TIMESTART4             1030
#define IDC_COMBO_OPTTYPE               1030
#define IDC_CHECK_RECONN                1030
#define IDC_EDIT_TIMEEND4               1031
#define IDC_LIST2                       1031
#define IDC_EDIT_RECVMOINTERVAL2        1031
#define IDC_EDIT_RECONNINTERVAL         1031
#define IDC_EDIT_TIMESTART2             1032
#define IDC_EDIT_TESTCONNINTERVAL       1032
#define IDC_EDIT_TIMEEND2               1033
#define IDC_BUTTON1                     1033
#define IDC_BTN_ADD_FIELD               1033
#define IDC_BTN_SEND                    1033
#define IDC_EDIT_SPLITELEN_CHINANUM     1033
#define IDC_EDIT_INFOTYPE               1034
#define IDC_EDIT_SPLITELEN3             1034
#define IDC_EDIT_SPLITELEN_CHINACOM     1034
#define IDC_EDIT_MOBILE                 1035
#define IDC_EDIT_RECVSTATUS3            1035
#define IDC_EDIT_UNICOM                 1036
#define IDC_EDIT_SENDSTATUS1            1036
#define IDC_EDIT_TELECOM                1037
#define IDC_EDIT_SENDSTATUS3            1037
#define IDC_EDIT_SPLITERCHAR            1037
#define IDC_EDIT_TIMEREADSTART          1038
#define IDC_CHECK_HISTRY                1038
#define IDC_EDIT_TIMEEND6               1039
#define IDC_EDIT_TIMEREADEND            1039
#define IDC_EDIT_MAINPORT               1039
#define IDC_CHECK_RECVTABLE             1040
#define IDC_EDIT_TIMEREADEND2           1040
#define IDC_EDIT_SUBPORTLEN             1040
#define IDC_CHECK_SYSRUN                1040
#define IDC_EDIT_HISTRYFORMAT           1041
#define IDC_EDIT_READNUMNAME            1041
#define IDC_EDIT_SPLITELEN_UNICOM       1041
#define IDC_EDIT_RECVFORMAT             1042
#define IDC_WINDOWNAME                  1042
#define IDC_EDIT_SPGATE                 1042
#define IDC_RADIO_MSSQL                 1043
#define IDC_RADIO_ORACLE                1044
#define IDC_RADIO_MYSQL                 1045
#define IDC_RADIO4                      1046
#define IDC_RADIO_ACCESS                1046
#define IDC_STATIC_CHARSET              1047
#define IDC_EDIT_PHONE                  1048
#define IDC_RADIO_KEXINTONG             1048
#define IDC_RADIO_SI                    1049
#define IDC_EDIT_SUBPORT                1049
#define IDC_CHECK_LOG2                  1050
#define IDC_CHECK_NEEDRPT               1050
#define ID_MENU_RUN                     32774
#define ID_MENU_SET                     32775
#define ID_MENU_CHECKFEE                32776
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32785                  32785
#define ID_MENU_STOP                    32795
#define ID_Menu                         32800
#define ID_32801                        32801
#define ID_APP_QUIT                     32802
#define ID_LST_DELETE                   32805
#define ID_MENU_INSERT                  32806
#define ID_MENU_INSERTOWN               32807
#define ID_LST_DELETEOWN                32808
#define ID_32823                        32823
#define ID_MENU_SINGLESEND              32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
